[build]
  publish = "OS"
  command = "echo 'Static site deployment - no build needed'"
  
[build.environment]
  NODE_VERSION = "18"
  DISABLE_PYTHON_INSTALLATION = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' http://localhost:11434; img-src 'self' data:; connect-src 'self' http://localhost:11434 https://api.netlify.com;"